## NumPy

Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices,along with a collection of mathematical functions to operate on these data structures.In this lesson,we will cover the basics of NumPy,focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

In [2]:
import numpy as np

## create array using numpy
## create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape) ## (5,) got print that mean its single dimension array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


now this is two dimension array bcoz of two braces [[]]

In [3]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [4]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In a 2D NumPy array every row must have equal number of elements — just like a proper table or matrix in mathematics.
This concept becomes very important in ML because your dataset rows must all have the same number of features. ✅

In [ ]:
arr2=np.array([[1,2,3,4,5],[7,8,9,10]]) ## it will show error over here
print(arr2)
print(arr2.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [9]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

for creating array

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Identity matrix creation

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Attribute of numpy

In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size (number of elements):",arr.size)
print("Data type:",arr.dtype) ## output:int64 (may vary based on platform)
print("Item size (in bytes):",arr.itemsize) ##output: 8(may vary based on platform)

Array:
 [[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
Number of dimensions: 2
Size (number of elements): 8
Data type: int64
Item size (in bytes): 8


Numpy vectorized operation

element wise operation

In [19]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10]) ## if any of one size not same then this operation will not work

print("Addition:",arr1+arr2)

print("Subtraction:",arr1-arr2)

print("Multiplication:",arr1*arr2)

print("Division:",arr1/arr2)

Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


Universal Function(apply on entire array)

In [ ]:
arr=np.array([1,2,3,4,5])

print(np.sqrt(arr))

print(np.exp(arr))

print(np.sin(arr))

print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


array slicing and Indexing

In [23]:
arr=np.array([[1,2,3,4],[4,5,6,7],[6,7,8,9]])
print("Array : \n",arr)

Array : 
 [[1 2 3 4]
 [4 5 6 7]
 [6 7 8 9]]


In [ ]:
## accessing the element of the array
print(arr[1,1])
  
print(arr[0:2,2:]) ##output 3,4,6,7  (0 se 2(before 2 mean include 1) index tak aur 2 ke baad)

print("\n",arr[0:2,0:2],"\n") #output 1,2,4,5

print(arr[1,1:3])  ##output 5 and 6

arr[1:]



5
[[3 4]
 [6 7]]

 [[1 2]
 [4 5]] 

[5 6]


array([[4, 5, 6, 7],
       [6, 7, 8, 9]])

In [29]:
arr[1:,2:]

array([[6, 7],
       [8, 9]])

Modifiy array element

In [ ]:
arr[0,0]=100
print(arr)



[[100   2   3   4]
 [  4   5   6   7]
 [  6   7   8   9]]


In [41]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


Statistical concepts --Normalization

to have a mean of 0 and standard deviation of 1

In [42]:
data = np.array([1,2,3,4,5])

#calculate the mean and standard deviation

mean=np.mean(data)
std_dev=np.std(data)

#normalize the data
normalized_data=(data-mean)/ std_dev
print("Normalized data : ",normalized_data)



Normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


calculating mean,median,standard_Deviation and variance

In [43]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean=np.mean(data)
print("mean:",mean)

#Median
median=np.median(data)
print("median: ",median)

#standard deviation

std_dev=np.std(data)
print("Standard Deviation: ",std_dev)

#Variance

variance=np.var(data)
print("Variance : ",variance)

mean: 5.5
median:  5.5
Standard Deviation:  2.8722813232690143
Variance :  8.25


In [55]:
# <!-- logical operation -->

data=np.array([1,2,3,4,5,6,7,8,9,10])
data>5



array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [56]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [57]:
print(data[data>5])

[ 6  7  8  9 10]


In [63]:
print(data[(data>5) & (data<8)])

[6 7]
